version: 2

project_name: orgtop

builds:
  - id: orgtop
    main: ./cmd/orgtop
    binary: orgtop
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/fmueller/orgtop/internal/cli.Version={{ .Version }}

archives:
  - id: orgtop
    ids:
      - orgtop
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  disable: true
